name: CI-CD Pipeline with AutoScaler

on:
  push:
    branches: [master]


jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Create custom Docker network
        run: docker network create sage-net

      - name: Prepare NGINX config
        run: |
          mkdir -p nginx_conf
          cp nginx/default.conf nginx_conf/

      - name: Build App Image
        run: docker build -t sage -f Dockerfile .

      - name: Build AutoScaler Image
        run: docker build -t autoscaler -f Dockerfile.autoscaler .

      - name: Run App Container
        run: docker run -d --name app_5001 --network sage-net -p 5001:5001 sage

      - name: Run NGINX Container
        run: |
          docker run -d --name nginx \
            --network sage-net \
            -p 80:80 \
            -v ${{ github.workspace }}/nginx_conf/default.conf:/etc/nginx/conf.d/default.conf \
            nginx

      - name: Run AutoScaler Container
        run: |
          docker run -d --name scaler \
            --network sage-net \
            -v /var/run/docker.sock:/var/run/docker.sock \
            autoscaler
