name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flask

    - name: Run tests
      run: |
        pytest tests/

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd /home/ubuntu
          if [ ! -d "SAGE" ]; then
            git clone https://github.com/Srinithish-dev/SAGE.git
          fi
          cd SAGE
          git pull origin master

          sudo docker stop nginx || true
          sudo docker rm nginx || true
          sudo docker stop app_5001 || true
          sudo docker rm app_5001 || true

          sudo docker build -t sage .
          sudo docker run -d --name app_5001 -p 5001:5001 -e FLASK_PORT=5001 sage
          sudo docker run -d --name nginx -p 80:80 -v $(pwd)/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro nginx
          sudo pkill -f auto_scaler.py || true
          nohup sudo python3 auto_scaler.py > scaler.log 2>&1 &
