name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Build Docker Image
        run: docker build -t sage .

      - name: Create Docker Network
        run: docker network create sage-net

      - name: Run Flask App Container
        run: docker run -d --name app_5001 --network sage-net sage

      - name: Run NGINX Container
        run: |
          docker run -d --name nginx \
            --network sage-net \
            -p 80:80 \
            -v ${{ github.workspace }}/default.conf:/etc/nginx/conf.d/default.conf:ro \
            nginx

      - name: Install AutoScaler Dependencies
        run: pip install docker psutil requests

      - name: Start AutoScaler and Keep Job Alive
        run: |
          python3 auto_scaler.py &  # Start auto scaler in background
          echo "AutoScaler is running..."
          tail -f /dev/null         # Keep GitHub Actions alive
